name: flutter_localizations_plus
description: An enhanced Flutter localization one-stop solution that streamlines multilingual integration for seamless app development.
homepage: https://github.com/leo1394/flutter_localizations_plus
repository: https://github.com/leo1394/flutter_localizations_plus
issue_tracker: https://github.com/leo1394/flutter_localizations_plus/issues
version: 0.2.4
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - locale/     # for multiple languages

topics:
  - localizations
  - locale
  - l10n
  - i18n
